#!/usr/bin/env python3
"""
embed_dashboard.py — viz/dashboard.html 을 gzip 압축해
ESP32 펌웨어 헤더(dashboard_html.h)로 변환.

대시보드 수정 후 반드시 재실행할 것:
    python3 tools/embed_dashboard.py
"""
import gzip
from pathlib import Path

root = Path(__file__).resolve().parent.parent
src = (root / "viz" / "dashboard.html").read_bytes()
gz = gzip.compress(src, 9)

out = root / "esp32" / "edge_alimi" / "dashboard_html.h"
lines = [
    "/* auto-generated by tools/embed_dashboard.py — DO NOT EDIT.",
    f" * source: viz/dashboard.html ({len(src)} B -> gzip {len(gz)} B) */",
    "#pragma once",
    "#include <stdint.h>",
    "#if defined(ARDUINO)",
    "#include <pgmspace.h>",
    "#else",
    "#ifndef PROGMEM",
    "#define PROGMEM",
    "#endif",
    "#endif",
    f"#define DASHBOARD_HTML_GZ_LEN {len(gz)}u",
    "static const uint8_t DASHBOARD_HTML_GZ[] PROGMEM = {",
]
for i in range(0, len(gz), 20):
    lines.append("  " + ",".join(str(b) for b in gz[i:i+20]) + ",")
lines.append("};")
out.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"embedded: {len(src)} B -> {len(gz)} B gzip -> {out.relative_to(root)}")
